### ISSUE TITLE
[Todo] Add missing APIs (0.7.x)

### ISSUE THREAD

**Issue by zaydek** [zaydek/duomo#155]
- [x] Transform origin
- [x] Revised font-weight https://github.com/zaydek/duomo/pull/159
- [ ] Square / circle APIs https://github.com/zaydek/duomo/issues/156
  - [ ] This should be OK since we are not relying on `flex-shrink` heuristics anymore
- [ ] ~~Border styles~~

**Comment by zaydek** [comment]
`origin-t`, etc.

**Comment by zaydek** [comment]
Can defer to 0.7.1.
